import { ModelInfo, TrackInfo, TrackResponse } from './models';

export const sampleResponse: TrackResponse = {
  count: 254604,
  records: [
    {
      ID: 406068,
      title: 'Mosaic FSET-718 My Sister&#039;s Videos 2 Of My Sister Tajima Masaki - javdoe.sh ',
      src: 'https://javdoe.sh/embed/262224/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/262/224/1.jpg',
      URL: 'https://javdoe.sh/262224/mosaic-fset-718-my-sister-s-videos-2-of-my-sister-tajima-masaki/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406068,
          ID: 1656,
          Name: 'Hakutou Kokona',
          image: 'https://i0.wp.com/img.hpav.tv/models/hakutou-kokona.jpg',
        },
      ],
      studio: 'fset',
      Key: 'fset-718',
    },
    {
      ID: 406067,
      title:
        'Mosaic RBD-817 推川 Day That My Sister Has Become Something Only My Yuri White Peach Kokorona - javdoe.sh ',
      src: 'https://javdoe.sh/embed/229207/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/229/207/1.jpg',
      URL: 'https://javdoe.sh/229207/mosaic-rbd-817-%E6%8E%A8%E5%B7%9D-day-that-my-sister-has-become-something-only-my-yuri-white-peach-kokorona/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406067,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406067,
          ID: 1656,
          Name: 'Hakutou Kokona',
          image: 'https://i0.wp.com/img.hpav.tv/models/hakutou-kokona.jpg',
        },
      ],
      studio: 'rbd',
      Key: 'rbd-817',
    },
    {
      ID: 406066,
      title:
        'NHDTB-130 A Bite-bye Girl Who Is Occupied The Shop In Business And Becomes A Person Who Exposes In A Completely Sealed Space - javdoe.sh ',
      src: 'https://javdoe.sh/embed/233330/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/233/330/1.jpg',
      URL: 'https://javdoe.sh/233330/nhdtb-130-a-bite-bye-girl-who-is-occupied-the-shop-in-business-and-becomes-a-person-who-exposes-in-a-completely-sealed-space/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406066,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406066,
          ID: 1467,
          Name: 'Akemi Kou',
          image: 'https://jav-fetish.com/wp-content/uploads/2019/10/7d2b_b-1-245x351.jpg',
        },
        {
          trackFk: 406066,
          ID: 2132,
          Name: 'Hatsumi Rin',
          image: 'https://javtube.com/javpic/rin-hatsumi/21/rin-hatsumi-1.jpg',
        },
        {
          trackFk: 406066,
          ID: 8261,
          Name: 'Sugisaki Shizuka',
          image: 'https://www.asianscreens.com/products/400000/portraits/shizuka_sugisaki.jpg',
        },
      ],
      studio: 'nhdtb',
      Key: 'nhdtb-130',
    },
    {
      ID: 406065,
      title:
        'NASK-215 In Fact, I Was Totally Into My Mother, But I Was Alone In A Mixed Bath... I Let My Guard Down Because She Was Just A Child, And When I Saw Her Naked Body, I Got A Rock Hard Erection. This Is The Whole Story Of The Mistake I Made. - javdoe.sh ',
      src: 'https://javdoe.sh/embed/253616/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/253/616/1.jpg',
      URL: 'https://javdoe.sh/253616/nask-215-in-fact-i-was-totally-into-my-mother-but-i-was-alone-in-a-mixed-bath-i-let-my-guard-down-because-she-was-just-a-child-and-when-i-saw-her-naked-body-i-got-a-rock-hard-erection-this-is-the-whole-story-of-the-mistake-i-made/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: {
        type: 'Buffer',
        data: [1],
      },
      models: [
        {
          trackFk: 406065,
          ID: 2829,
          Name: 'Honjou Hitomi',
          image: 'https://12111549.pix-cdn.org/contents/models/54820/hitomi_honjo.jpg',
        },
        {
          trackFk: 406065,
          ID: 1772,
          Name: 'Oda Mako',
          image: 'https://media.tits-guru.com/images/c814b747-85aa-4e11-936f-0b85122a3076.jpeg',
        },
        {
          trackFk: 406065,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406065,
          ID: 7934,
          Name: 'Itou Sara',
          image: 'https://javpornpics.com/r18/sara-ito/h_796san00002/hd-sara-ito-0.jpg',
        },
        {
          trackFk: 406065,
          ID: 10567,
          Name: 'Nakano Nao',
          image: 'https://hidefporn.ws/uploads/posts/2021-04/1618142626_7621_hidefporn_ws.jpg',
        },
        {
          trackFk: 406065,
          ID: 10500,
          Name: 'Hirose Yuka',
          image: 'https://javhdporntube.com/video/yuuka-hirose/h_067natr00635/yuuka-hirose-5.jpg',
        },
      ],
      studio: 'nask',
      Key: 'nask-215',
    },
    {
      ID: 406064,
      title:
        'Mosaic UMD-951 The Queen Of Hidden Options!! She Has The Skill To Make All Three Men Cum And A Variety Of Options You&#039;ve Never Experienced Before!! This Is The Masterful Technique Of A Reflexology Girl!! - javdoe.sh ',
      src: 'https://javdoe.sh/embed/247919/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/247/919/1.jpg',
      URL: 'https://javdoe.sh/247919/mosaic-umd-951-the-queen-of-hidden-options-she-has-the-skill-to-make-all-three-men-cum-and-a-variety-of-options-you-ve-never-experienced-before-this-is-the-masterful-technique-of-a-reflexology-girl/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406064,
          ID: 2045,
          Name: 'Hasumi Kurea',
          image:
            'https://ci.phncdn.com/pics/pornstars/000/272/022/(m=lciuhScOb_c)(mh=eI_ZoBFy1ZkY6xYu)thumb_627731.jpg',
        },
        {
          trackFk: 406064,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406064,
          ID: 121,
          Name: 'Mukai Ai',
          image: 'https://fs.xcity.jp/imgsrc/image/maker/orga/tamm015/f_1499662550_1.jpg',
        },
        {
          trackFk: 406064,
          ID: 15642,
          Name: 'Niimura Akari',
          image:
            'https://javcl.com/wp-content/uploads/2021/11/cemd-089-wet-anal-sex-akari-niimura-cumming-so-man.jpg',
        },
        {
          trackFk: 406064,
          ID: 4274,
          Name: 'Hoshi Ameri',
          image:
            'https://ravecloud.xyz/2019/03/request7Burl3A22http3A2F2Fwarashi-asian-pornstars.fr2FWAPdB-img2Fpornostars-f2Fa2Fm2F36182Fameri-hoshi2Fprofil-22Flarge2Fwapdb-ameri-hoshi-pornostar-asiatique.warashi-asian-pornstars.fr_.jpg',
        },
        {
          trackFk: 406064,
          ID: 4298,
          Name: 'Fukada Yuuri',
          image: 'https://javtube.com/javpic/yuri-fukada/5/yuri-fukada-12.jpg',
        },
        {
          trackFk: 406064,
          ID: 11236,
          Name: 'Himesaki Hana',
          image:
            'https://javcl.com/wp-content/uploads/2021/04/aphrodisiac-addled-sex-bangin-in-a-shared-room-cre.jpg',
        },
        {
          trackFk: 406064,
          ID: 10956,
          Name: 'Satsuki Mei',
          image: 'https://img.pornfhd.com/wp-content/uploads/2020/12/dvdms-611.jpg',
        },
        {
          trackFk: 406064,
          ID: 12073,
          Name: 'Ichiki Mahiro',
          image: 'https://javbtc.com/video/mahiro-ichiki/tikp00055/hd-mahiro-ichiki-0.jpg',
        },
        {
          trackFk: 406064,
          ID: 13200,
          Name: 'Hironaka Minami',
          image: 'https://javhd.pics/dmm/minami-hironaka/mifd00165/minami-hironaka-1.jpg',
        },
      ],
      studio: 'umd',
      Key: 'umd-951',
    },
    {
      ID: 406063,
      title: 'Mosaic GVH-514 Busty Mama&#039;s Compensation Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/256777/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/256/777/1.jpg',
      URL: 'https://javdoe.sh/256777/mosaic-gvh-514-busty-mama-s-compensation-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406063,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'gvh',
      Key: 'gvh-514',
    },
    {
      ID: 406062,
      title: 'CMI-127 Girls&#039; Extreme Image Human Wife 28th Person - javdoe.sh ',
      src: 'https://javdoe.sh/embed/262376/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/262/376/1.jpg',
      URL: 'https://javdoe.sh/262376/cmi-127-girls-extreme-image-human-wife-28th-person/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406062,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'cmi',
      Key: 'cmi-127',
    },
    {
      ID: 406061,
      title:
        'JUR-338 I Could Never Tell My Wife That I Impregnated Her Mother ... On A Two-days And One-night Trip To The Hot Spring, I Lost Control And Kept Cumming Inside Her Over And Over Again - Oshikawa Yuuri - javdoe.sh ',
      src: 'https://javdoe.sh/embed/263235/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/263/235/1.jpg',
      URL: 'https://javdoe.sh/263235/jur-338-i-could-never-tell-my-wife-that-i-impregnated-her-mother-on-a-two-days-and-one-night-trip-to-the-hot-spring-i-lost-control-and-kept-cumming-inside-her-over-and-over-again-oshikawa-yuuri/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: {
        type: 'Buffer',
        data: [1],
      },
      models: [
        {
          trackFk: 406061,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'jur',
      Key: 'jur-338',
    },
    {
      ID: 406060,
      title:
        'Mosaic FSET-766 Nature Nymphos I Became A Prey Of Sexual Desire Which The Nurse Can Not Control - javdoe.sh ',
      src: 'https://javdoe.sh/embed/261313/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/261/313/1.jpg',
      URL: 'https://javdoe.sh/261313/mosaic-fset-766-nature-nymphos-i-became-a-prey-of-sexual-desire-which-the-nurse-can-not-control/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406060,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406060,
          ID: 1657,
          Name: 'Mari Rika',
          image: 'https://javbtc.com/media/japanese/rika-mari/14/hd-rika-mari-6.jpg',
        },
        {
          trackFk: 406060,
          ID: 16961,
          Name: 'Toyooka Satsuki',
          image: null,
        },
      ],
      studio: 'fset',
      Key: 'fset-766',
    },
    {
      ID: 406059,
      title:
        'JUR-447 The Workplace That Was Introduced As A Healthy Beauty Salon Turned Out To Be An Erotic Beauty Salon... A Married Woman Who Was Trained To Be Obedient By The Sleazy Manager&#039;s Sexual Harassment Training. Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/264981/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/264/981/1.jpg',
      URL: 'https://javdoe.sh/264981/jur-447-the-workplace-that-was-introduced-as-a-healthy-beauty-salon-turned-out-to-be-an-erotic-beauty-salon-a-married-woman-who-was-trained-to-be-obedient-by-the-sleazy-manager-s-sexual-harassment-training-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406059,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
        {
          trackFk: 406059,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'jur',
      Key: 'jur-447',
    },
    {
      ID: 406058,
      title: 'KSBJ-043 Barefoot Wife Hiroshi Onukawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/265883/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/265/883/1.jpg',
      URL: 'https://javdoe.sh/265883/ksbj-043-barefoot-wife-hiroshi-onukawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406058,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'ksbj',
      Key: 'ksbj-043',
    },
    {
      ID: 406057,
      title: 'Mosaic NACT-051 Masochistic Awakening Married Woman Slave Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/268696/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/268/696/1.jpg',
      URL: 'https://javdoe.sh/268696/mosaic-nact-051-masochistic-awakening-married-woman-slave-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406057,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
        {
          trackFk: 406057,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'nact',
      Key: 'nact-051',
    },
    {
      ID: 406056,
      title:
        'Mosaic BBTU-049 Bikini Explosion Big Tits Bomber Pie Shattered Ball Yuri Hikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/271633/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/271/633/1.jpg',
      URL: 'https://javdoe.sh/271633/mosaic-bbtu-049-bikini-explosion-big-tits-bomber-pie-shattered-ball-yuri-hikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406056,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'bbtu',
      Key: 'bbtu-049',
    },
    {
      ID: 406055,
      title: 'GVH-815 Mother-son Incest Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/273029/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/273/029/1.jpg',
      URL: 'https://javdoe.sh/273029/gvh-815-mother-son-incest-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406055,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
        {
          trackFk: 406055,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
      ],
      studio: 'gvh',
      Key: 'gvh-815',
    },
    {
      ID: 406054,
      title: 'English Sub GVH-154 Three Generations Incest IV - javdoe.sh ',
      src: 'https://javdoe.sh/embed/275114/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/275/114/1.jpg',
      URL: 'https://javdoe.sh/275114/english-sub-gvh-154-three-generations-incest-iv/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406054,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
        {
          trackFk: 406054,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406054,
          ID: 6877,
          Name: 'Hiraoka Rieko',
          image:
            'https://javcl.com/wp-content/uploads/2021/10/i-was-seduced-by-my-stepmom-that-time-rieko-hiraok.jpg',
        },
        {
          trackFk: 406054,
          ID: 8581,
          Name: 'Mikamo Rika',
          image:
            'https://javcl.com/wp-content/uploads/2020/11/10-people-cum-to-tits-beautiful-naked-girl-183x233.jpg',
        },
        {
          trackFk: 406054,
          ID: 1223,
          Name: 'Tachibana Yuuka',
          image:
            'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRrF_Q1IIsUor8N-5DR9EY5a9cGUMrSyzf2MiWXKGdJTSjM4191Sw',
        },
      ],
      studio: 'gvh',
      Key: 'gvh-154',
    },
    {
      ID: 406053,
      title:
        'OVG-079 Married Wife Crawled Next To Her Husband Sleeping In The Middle Of The Night Crawling In The Middle Of The Night - javdoe.sh ',
      src: 'https://javdoe.sh/embed/275299/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/275/299/1.jpg',
      URL: 'https://javdoe.sh/275299/ovg-079-married-wife-crawled-next-to-her-husband-sleeping-in-the-middle-of-the-night-crawling-in-the-middle-of-the-night/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406053,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
        {
          trackFk: 406053,
          ID: 4678,
          Name: 'Mori Nanako',
          image:
            'https://static-ca-cdn.eporner.com/gallery/9Q/OR/3qbYZouOR9Q/790597-nanako-mori-nude.jpg',
        },
        {
          trackFk: 406053,
          ID: 1661,
          Name: 'Oshikawa Yuuri',
          image: 'https://www.tubetubetube.com/pics/japanese/yuuri-oshikawa/8/yuuri-oshikawa-8.jpg',
        },
        {
          trackFk: 406053,
          ID: 1811,
          Name: 'Nonomiya Misato',
          image: 'https://tn.upornia.com/contents/models/390262/r240x400_1.jpg',
        },
        {
          trackFk: 406053,
          ID: 2566,
          Name: 'Maeta Kanako',
          image: 'https://javseen.tv/media/videos/tmb/000/008/915/1.jpg',
        },
        {
          trackFk: 406053,
          ID: 1900,
          Name: 'Shura Ishikura',
          image:
            'https://i1.wp.com/javcl.com/wp-content/uploads/2018/05/gvg-593-boyne-i-love-shota-kuns-hankanizura-isakur-340x520.jpg',
        },
      ],
      studio: 'ovg',
      Key: 'ovg-079',
    },
    {
      ID: 406052,
      title: 'ADN-759 Please Forgive Me... Lost Memories 6 Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/276716/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/276/716/1.jpg',
      URL: 'https://javdoe.sh/276716/adn-759-please-forgive-me-lost-memories-6-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406052,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'adn',
      Key: 'adn-759',
    },
    {
      ID: 406051,
      title:
        'Mosaic NGOD-163 It&#039;s So Boring In The Country Because There&#039;s Nothing To Do, But Then My Beautiful Step Auntie Deflowered My Cherry Boy Ass By Getting Down And Sweaty, And I Could See Her Body Through Her Wet Clothes, And She Fucked My Brains Ou',
      src: 'https://javdoe.sh/embed/277006/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/277/006/1.jpg',
      URL: 'https://javdoe.to/search/movie/ngod-163',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406051,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'ngod',
      Key: 'ngod-163',
    },
    {
      ID: 406050,
      title:
        'English sub JUR-217 I Picked Up A Lost Lamb-like I-cup Busty Wife, And The Record Of The Few Days I Spent With Her In Super Carnivorous Wolf-like Sex That Made Me Cum Over And Over Again. Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/276821/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/276/821/1.jpg',
      URL: 'https://javdoe.sh/276821/english-sub-jur-217-i-picked-up-a-lost-lamb-like-i-cup-busty-wife-and-the-record-of-the-few-days-i-spent-with-her-in-super-carnivorous-wolf-like-sex-that-made-me-cum-over-and-over-again-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406050,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'jur',
      Key: 'jur-217',
    },
    {
      ID: 406049,
      title: 'Mosaic NGOD-164 Woman at Convenience Store Headquarters 9 Yuri Oshikawa - javdoe.sh ',
      src: 'https://javdoe.sh/embed/277725/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/277/725/1.jpg',
      URL: 'https://javdoe.sh/277725/mosaic-ngod-164-woman-at-convenience-store-headquarters-9-yuri-oshikawa/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406049,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'ngod',
      Key: 'ngod-164',
    },
    {
      ID: 406048,
      title:
        'English Sub JUR-180 I Wanted To Make My Horny Co-worker Admit His Wrong About His Claim That Married Women Are Easy To Fuck, So I Agreed To Put My Wife To A Fidelity Test And Ended Up Inviting Him Home To Tempt Her. I Left Her Alone With Him For 3 Hours..',
      src: 'https://javdoe.sh/embed/277924/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/277/924/1.jpg',
      URL: 'https://javdoe.to/search/movie/jur-180',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406048,
          ID: 3999,
          Name: 'Yuri Oshikawa',
          image: 'https://roshy.tv/wp-content/uploads/2022/08/venx152pl1-358x538.jpg',
        },
      ],
      studio: 'jur',
      Key: 'jur-180',
    },
    {
      ID: 406047,
      title:
        'English Sub MIDA-005 A Girl In A School Uniform Has Her Huge Breasts Massaged To Orgasm With An Aphrodisiac, Toa Yuki - javdoe.sh ',
      src: 'https://javdoe.sh/embed/278269/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/278/269/1.jpg',
      URL: 'https://javdoe.sh/278269/english-sub-mida-005-a-girl-in-a-school-uniform-has-her-huge-breasts-massaged-to-orgasm-with-an-aphrodisiac-toa-yuki/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406047,
          ID: 17332,
          Name: 'Yuuki Toa',
          image: null,
        },
      ],
      studio: 'mida',
      Key: 'mida-005',
    },
    {
      ID: 406046,
      title:
        'Mosaic WTEX-011 Cosplay Support. G-cup Cosplayer Rika, A Nerd And A Creampie Bukkake Orgy, Is Trained To Be Obedient And Used As A Masturbator! 1000 Consecutive Orgasms Without A Condom, Resulting In Pregnancy! - javdoe.sh ',
      src: 'https://javdoe.sh/embed/278271/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/278/271/1.jpg',
      URL: 'https://javdoe.sh/278271/mosaic-wtex-011-cosplay-support-g-cup-cosplayer-rika-a-nerd-and-a-creampie-bukkake-orgy-is-trained-to-be-obedient-and-used-as-a-masturbator-1000-consecutive-orgasms-without-a-condom-resulting-in-pregnancy/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [],
      studio: 'wtex',
      Key: 'wtex-011',
    },
    {
      ID: 406045,
      title: 'English Sub JUY-325 Momoko Ichimiko I&#039;m Just A Beast - javdoe.sh ',
      src: 'https://javdoe.sh/embed/179692/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/179/692/1.jpg',
      URL: 'https://javdoe.sh/179692/english-sub-juy-325-momoko-ichimiko-i-m-just-a-beast/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406045,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'juy',
      Key: 'juy-325',
    },
    {
      ID: 406044,
      title:
        'ROE-229 Are You Sure This Is Okay A Wife Who Accepted Her Husband&#039;s Desire To Be Cuckolded Exhibits Creampie Sex Momoko Isshiki - javdoe.sh ',
      src: 'https://javdoe.sh/embed/206818/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/206/818/1.jpg',
      URL: 'https://javdoe.sh/206818/roe-229-are-you-sure-this-is-okay-a-wife-who-accepted-her-husband-s-desire-to-be-cuckolded-exhibits-creampie-sex-momoko-isshiki/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406044,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-229',
    },
    {
      ID: 406043,
      title:
        'English Sub ROE-179 The Moment Her Husband Leaves, In Just 2 Seconds Their Lips And Body Overlap, Mother-son Incest SEX, A Forbidden Urge That Cannot Be Suppressed. Momoko Isshiki - javdoe.sh ',
      src: 'https://javdoe.sh/embed/191067/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/191/067/1.jpg',
      URL: 'https://javdoe.sh/191067/english-sub-roe-179-the-moment-her-husband-leaves-in-just-2-seconds-their-lips-and-body-overlap-mother-son-incest-sex-a-forbidden-urge-that-cannot-be-suppressed-momoko-isshiki/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406043,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-179',
    },
    {
      ID: 406042,
      title:
        'English Sub ROE-186 Was Captivated By My Beautiful Aunt Wearing High Quality Corrective Underwear. Exclusive Momoko Isshiki&#039;s Beautiful Curves Will Make You Sigh. - javdoe.sh ',
      src: 'https://javdoe.sh/embed/192430/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/192/430/1.jpg',
      URL: 'https://javdoe.sh/192430/english-sub-roe-186-was-captivated-by-my-beautiful-aunt-wearing-high-quality-corrective-underwear-exclusive-momoko-isshiki-s-beautiful-curves-will-make-you-sigh/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406042,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-186',
    },
    {
      ID: 406041,
      title:
        'ROE-244 I Indulged In Massive Convulsive Sex With My Beloved Daughter&#039;s Boyfriend. - javdoe.sh ',
      src: 'https://javdoe.sh/embed/211004/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/211/004/1.jpg',
      URL: 'https://javdoe.sh/211004/roe-244-i-indulged-in-massive-convulsive-sex-with-my-beloved-daughter-s-boyfriend/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406041,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-244',
    },
    {
      ID: 406040,
      title:
        'English sub ROE-060 When Her Husband&#039;s Young Stepson Awakened To The Glories Of Sex, She Provided Him With Gentle And Furious Ejaculation Management With A Mother-In-Law&#039;s Sex Education Lession Momoko Isshiki - javdoe.sh ',
      src: 'https://javdoe.sh/embed/229567/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/229/567/1.jpg',
      URL: 'https://javdoe.sh/229567/english-sub-roe-060-when-her-husband-s-young-stepson-awakened-to-the-glories-of-sex-she-provided-him-with-gentle-and-furious-ejaculation-management-with-a-mother-in-law-s-sex-education-lession-momoko-isshiki/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406040,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-060',
    },
    {
      ID: 406039,
      title:
        'English Sub ROE-177 I Was Treated Like A Toy At My Son&#039;s Boarding House. Momoko Isshiki Keeps Being Raped By Her Housemate... - javdoe.sh ',
      src: 'https://javdoe.sh/embed/205703/',
      image: 'https://pics.javdoe.sh/media/videos/tmb//000/205/703/1.jpg',
      URL: 'https://javdoe.sh/205703/english-sub-roe-177-i-was-treated-like-a-toy-at-my-son-s-boarding-house-momoko-isshiki-keeps-being-raped-by-her-housemate/',
      domain: 'javdoe.sh',
      dateAdded: null,
      modelFk: 0,
      width: 640,
      height: 360,
      favorite: null,
      models: [
        {
          trackFk: 406039,
          ID: 2321,
          Name: 'Isshiki Momoko',
          image: 'https://roshy.tv/wp-content/uploads/2024/01/jul517pl1-358x538.jpg.webp',
        },
      ],
      studio: 'roe',
      Key: 'roe-177',
    },
  ],
};

export const sampleTrack: TrackInfo = sampleResponse.records[2];

export const sampleModel: ModelInfo[] = sampleTrack.models;

export const SEARCH_SEED = [
  'dad|papa|daught|father',
  'tiny tit|a-cup|a cup|13*cm|14*cm',
  'mom|mother|son',
  'wife,protect|debt|please|forgive|sorry|reason|father|boss|rape',
  'walks in on|next to|in front of|behind her back',
  'rape|molest|attack',
  'mom|mother|stepson',
  'big  dick|bigdick|monster cock|huge cock|big cock|horse cock|horse hung',
  'nurse|hosp',
  'shirt|no bra |see-through|see through|sheer',
  'panti|panch|panty shot|pantyshot',
  '3p|dp|threesome',
  'caba|pub |pinsa',
  'booty| ass |butt',
  'lesb|girlsway',
  'wank|jerk|masturbat|strokes|stroking',
  'self-suck|self suck|selfsuck',
  'dp |3p',
  'aphro|drug|potion',
  'shemale|she-male|tranny|transex| ts |ladyboy|lady boy',
];
